Manual and sonarcloud review
BME-MIT-IET/iet-hf-2024-nomad-szabotorok pull request #6
Opened 2024-05-16 16:24 UTC by ErikSkare

Test coverage passing is not required here. Tests will be implemented in issue https://github.com/BME-MIT-IET/iet-hf-2024-nomad-szabotorok/issues/2.

2024-05-17 08:33 UTC, wittmajerd approved these changes
Átnéztem és mindent rendben találtam, annyi még hogy egy rövid feladat dokumentációt írj még a doc mappába

2024-05-17 11:16 UTC, Peter200204 approved these changes
Rendben van.

2024-05-18 16:04 UTC, tanaiadam requested changes
Új sort tegyél a fájlok végére (dockerfile, gitignore stb.)
Kompatibilitás szempontból előnyös.

2024-05-18 16:04 UTC, tanaiadam commented on .gitignore
Mehetett volna bele az *.idea is.

2024-05-19 16:59 UTC, tanaiadam approved these changes

2024-05-19 17:00 UTC, merged